producer.compression.type=snappy
group.id=compose-connect-group
value.converter.schemas.enable=false
status.storage.cleanup.policy=compact
config.storage.cleanup.policy=compact
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
config.storage.topic=docker-connect-configs
log4j.loggers=org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR
offset.storage.replication.factor=1
plugin.path=/usr/local/share/java,/usr/local/share/kafka/plugins,/opt/connectors
log4j.root.loglevel=INFO
offset.storage.topic=docker-connect-offsets
key.converter.schemas.enable=false
bootstrap.servers=kafka:29092
value.converter=org.apache.kafka.connect.json.JsonConverter
producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
rest.advertised.host.name=kafka-connect
offset.storage.cleanup.policy=compact
rest.port=8083
status.storage.topic=docker-connect-status
consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
config.storage.replication.factor=1
